variables:
  GLOBAL_VAR: "A global variable"

job1:
  variables: {}
  script:
    - echo This job does not need any variables

build-job:
  variables:
    JOB_VAR: "A job variable"
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"
    - echo "The job's stage is '$CI_JOB_STAGE'"
    - echo "Variables are '$GLOBAL_VAR' and '$JOB_VAR'"

test-job1:
  stage: test
  script:
    - echo "This job tests something"
    - echo "The job's stage is '$CI_JOB_STAGE'"
    - echo "Variables are '$GLOBAL_VAR' and '$JOB_VAR'"

test-job2:
  stage: test
  script:
    - echo "This job tests something, but takes more time than test-job1."
    - echo "After the echo commands complete, it runs the sleep command for 20 seconds"
    - echo "which simulates a test that runs 20 seconds longer than test-job1"
    - sleep 20

deploy-prod:
  stage: deploy
  script:
    - echo "The job's stage is '$CI_JOB_STAGE'"
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
  environment: production
